/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'items' : Array<CartItem> }
export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Category { 'id' : bigint, 'name' : string }
export interface OrderData {
  'total' : bigint,
  'orderId' : bigint,
  'buyer' : Principal,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Product {
  'id' : bigint,
  'status' : ProductStatus,
  'title' : string,
  'description' : string,
  'stock' : bigint,
  'category' : string,
  'image' : string,
  'price' : bigint,
}
export type ProductStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'draft' : null };
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add admin privileges by email.
   * / Admin role required, or reserved for bootstrapping first admin.
   */
  'addAdminByEmail' : ActorMethod<[string], undefined>,
  /**
   * / Add admin privileges by principal.
   * / Admin role required, or reserved for bootstrapping first admin.
   */
  'addAdminByPrincipal' : ActorMethod<[Principal], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'approveProduct' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkCallerUserRole' : ActorMethod<[], UserRole>,
  'checkout' : ActorMethod<[], bigint>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCategory' : ActorMethod<[string], bigint>,
  'createProduct' : ActorMethod<[Product], bigint>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<OrderData>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], [] | [Cart]>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCategory' : ActorMethod<[bigint], [] | [Category]>,
  'getOrder' : ActorMethod<[bigint], [] | [OrderData]>,
  'getOrders' : ActorMethod<[], Array<OrderData>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[[] | [Principal]], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectProduct' : ActorMethod<[bigint], undefined>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCartItem' : ActorMethod<[bigint, bigint], undefined>,
  'updateCategory' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];